### ISSUE TITLE
Error on splunk_data_sender.SplunkSender()

### ISSUE THREAD

**Issue by ahmad4fifz** [ahmad4fifz/twitter-sentiment#3]
Error:

```bash
ERROR -- Error during authentication:
splunk_data_sender.SplunkSender() argument after ** must be a mapping, not SplunkSender
Traceback (most recent call last):
  File "/home/ahmad/Documents/GitHub/twitter-sentiment/tweet-sentiment.py", line 162, in <module>
    splunk = SplunkSender(**splunk_conf)
TypeError: splunk_data_sender.SplunkSender() argument after ** must be a mapping, not SplunkSender
__main__ - 2022-01-20 12:18:03,450 - ERROR: - Error during authentication:
splunk_data_sender.SplunkSender() argument after ** must be a mapping, not SplunkSender
Traceback (most recent call last):
  File "/home/ahmad/Documents/GitHub/twitter-sentiment/tweet-sentiment.py", line 162, in <module>
    splunk = SplunkSender(**splunk_conf)
TypeError: splunk_data_sender.SplunkSender() argument after ** must be a mapping, not SplunkSender
```

Any idea?

**Comment by ahmad4fifz** [comment]
not proceed using Splunk, move to ELK
