### ISSUE TITLE
Went wrong when using translation, type input used as int instead of strings

### ISSUE THREAD

**Issue by tx-qi** [ahmad4fifz/twitter-sentiment#5]
weepy.streaming - 2022-01-22 19:22:33,751 - ERROR: - Stream encountered an exception
Traceback (most recent call last):
  File "C:\Users\taqi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tweepy\streaming.py", line 133, in _connect
    self.on_data(line)
  File "C:\Users\taqi\Documents\Github\twitter-sentiment\tweet-sentiment.py", line 78, in on_data
    normalized= normalizer.normalize(str (tweet))
  File "C:\Users\taqi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\herpetologist\__init__.py", line 100, in check
    return func(*args, **kwargs)
  File "C:\Users\taqi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\malaya\normalize.py", line 511, in normalize
    word, repeat = check_repeat(word)
  File "C:\Users\taqi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\malaya\normalize.py", line 138, in check_repeat
    repeat = int(word[-1])
ValueError: invalid literal for int() with base 10: '²'

**Comment by tx-qi** [comment]
Fixed. added unicode removal so any unicode with lengthy integer removed.

`weet_unicode_removal=''.join([i if ord(i) < 128 else ' ' for i in tweet])
            tweet=tweet_unicode_removal`

**Comment by tx-qi** [comment]
wah hebaknye saya wahahaahh

**Comment by ahmad4fifz** [comment]
> wah hebaknye saya wahahaahh

apak ah
